using aiKart.Data;
using aiKart.Interfaces;
using aiKart.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using aiKart.States;


namespace aiKart.Repositories
{
    public class DeckRepository : IDeckRepository
    {
        private readonly DataContext _context;

        public DeckRepository(DataContext context)
        {
            _context = context;
        }

        //  async/await
        public async Task<Deck> GetDeckByIdAsync(int deckId)
        {
            return await _context.Decks
                                 .Include(deck => deck.Cards)  // Include the cards associated with the deck
                                 .FirstOrDefaultAsync(deck => deck.Id == deckId);
        }


        public IEnumerable<Deck> GetDecksIncludingCards()
        {
            return _context.Decks.Include(d => d.Cards).ToList();
        }

        public ICollection<Deck> GetDecks()
        {
            return _context.Decks.OrderBy(d => d.Id).ToList();
        }

        public Deck? GetDeck(int id)
        {
            return _context.Decks.Find(id);
        }

        public ICollection<Card> GetDeckCards(int deckId)
        {
            return _context.Cards
                .Where(c => c.DeckId == deckId).ToList();
        }

        public bool DeckExistsById(int id)
        {
            return _context.Decks.Any(d => d.Id == id);
        }

        public bool DeckExistsByName(string name)
        {
            return _context.Decks.Any(d => d.Name == name);
        }

        public bool AddDeck(Deck deck)
        {
            _context.Decks.Add(deck);
            return Save();
        }

        public bool DeleteDeck(Deck deck)
        {
            _context.Decks.Remove(deck);
            return Save();
        }

        public bool UpdateDeck(Deck deck)
        {
            _context.Decks.Update(deck);
            return Save();
        }

        public bool Save()
        {
            var saved = _context.SaveChanges();
            return saved > 0;
        }

        public async Task<Deck> CloneDeckAsync(Deck originalDeck)
        {
            var clonedDeck = new Deck
            {
                Name = originalDeck.Name,
                Description = originalDeck.Description,
                CreatorName = originalDeck.CreatorName,
                CreatorId = originalDeck.CreatorId,
                IsPublic = false,
                CreationDate = DateTime.UtcNow,
                LastEditDate = DateTime.UtcNow,
                // Do not include Cards initialization here, it will be done below
            };

            _context.Decks.Add(clonedDeck);
            await _context.SaveChangesAsync();  // Save to get the clonedDeck.Id generated by the database

            foreach (var card in originalDeck.Cards)
            {
                var clonedCard = new Card
                {
                    Question = card.Question,
                    Answer = card.Answer,
                    State = CardState.Unanswered,
                    DeckId = clonedDeck.Id  // Set the DeckId to associate with the cloned deck
                };

                _context.Cards.Add(clonedCard);
            }

            await _context.SaveChangesAsync(); // Save again to store the cards

            return clonedDeck;
        }


    }
}
